export default {
  SET_CURRENT_CATEGORY: 'SET_CURRENT_CATEGORY',
  SET_FINAL_SCORE: 'SET_FINAL_SCORE',
  SAVE_SCORE_SAGA: 'SAVE_SCORE_SAGA',
  LOAD_QUESTIONS_SAGA: 'LOAD_QUESTIONS_SAGA',
  SET_QUESTIONS: 'SET_QUESTIONS',
  SAVE_IS_MUTED_SAGA: 'SAVE_IS_MUTED_SAGA',
};
