export default {
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_SCORES: 'SET_SCORES',
  SET_IS_FAILED: 'SET_IS_FAILED',
  SET_IS_UPDATE_REQUIRED: 'SET_IS_UPDATE_REQUIRED',
  SET_IS_MUTED: 'SET_IS_MUTED',
  CHECK_UPDATE_SAGA: 'CHECK_UPDATE_SAGA',
  LOAD_ONLINE_DATA_SAGA: 'LOAD_ONLINE_DATA_SAGA',
  LOAD_OFFLINE_DATA_SAGA: 'LOAD_OFFLINE_DATA_SAGA',
  LOAD_SCORES_SAGA: 'LOAD_SCORES_SAGA',
  LOAD_IS_MUTED_SAGA: 'LOAD_IS_MUTED_SAGA',
};
