require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'bomdebiblia' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RealmJS', :path => '../node_modules/realm'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-admob', :path => '../node_modules/react-native-admob'

  pod 'RNExitApp', :path => '../node_modules/react-native-exit-app'



  pod 'RNSound', :path => '../node_modules/react-native-sound'

  target 'bomdebibliaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
